#release configuration
#Fri Jul 17 22:45:20 CDT 2026
projectVersionPolicyId=default
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
pinExternals=false
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
exec.activateProfiles=deploy-to-scijava
pushChanges=false
project.scm.io.scif\:scifio-labeling.connection=scm\:git\:git\://github.com/scifio/scifio-labeling
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
remoteTagging=true
scm.commentPrefix=[maven-release-plugin] 
releaseStrategyId=default
project.scm.io.scif\:scifio-labeling.url=https\://github.com/scifio/scifio-labeling
completedPhase=end-release
project.rel.io.scif\:scifio-labeling=0.4.0
scm.url=scm\:git\:https\://github.com/scifio/scifio-labeling
project.scm.io.scif\:scifio-labeling.developerConnection=scm\:git\:git@github.com\:scifio/scifio-labeling
scm.developmentCommitComment=@{prefix} prepare for next development iteration
project.scm.io.scif\:scifio-labeling.tag=HEAD
exec.additionalArguments=-Dgpg.skip\=true 
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.tag=scifio-labeling-0.4.0
project.dev.io.scif\:scifio-labeling=0.4.1-SNAPSHOT
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean verify
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
exec.pomFileName=pom.xml
